### ISSUE TITLE
Readiness probe failed

### ISSUE THREAD

**Issue by linonetwo** [LibreTranslate/helm-chart#4]
> (combined from similar events): Readiness probe failed: Traceback (most recent call last): File "/app/venv/lib/python3.11/site-packages/urllib3/connection.py", line 196, in _new_conn sock = connection.create_connection( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/app/venv/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection raise err File "/app/venv/lib/python3.11/site-packages/urllib3/util/connection.py", line 73, in create_connection sock.connect(sa) ConnectionRefusedError: [Errno 111] Connection refused The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/app/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 789, in urlopen response = self._make_request( ^^^^^^^^^^^^^^^^^^^ File "/app/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 495, in _make_request conn.request( File "/app/venv/lib/python3.11/site-packages/urllib3/connection.py", line 398, in request self.endheaders() File "/usr/local/lib/python3.11/http/client.py", line 1298, in endheaders self._send_output(message_body, encode_chunked=encode_chunked) File "/usr/local/lib/python3.11/http/client.py", line 1058, in _send_output self.send(msg) File "/usr/local/lib/python3.11/http/client.py", line 996, in send self.connect() File "/app/venv/lib/python3.11/site-packages/urllib3/connection.py", line 236, in connect self.sock = self._new_conn() ^^^^^^^^^^^^^^^^ File "/app/venv/lib/python3.11/site-packages/urllib3/connection.py", line 211, in _new_conn raise NewConnectionError( urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f6356f946d0>: Failed to establish a new connection: [Errno 111] Connection refused The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/app/venv/lib/python3.11/site-packages/requests/adapters.py", line 486, in send resp = conn.urlopen( ^^^^^^^^^^^^^ File "/app/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 843, in urlopen retries = retries.increment( ^^^^^^^^^^^^^^^^^^ File "/app/venv/lib/python3.11/site-packages/urllib3/util/retry.py", line 519, in increment raise MaxRetryError(_pool, url, reason) from reason # type: ignore[arg-type] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /translate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6356f946d0>: Failed to establish a new connection: [Errno 111] Connection refused')) During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/app/scripts/healthcheck.py", line 3, in <module> response = requests.post( ^^^^^^^^^^^^^^ File "/app/venv/lib/python3.11/site-packages/requests/api.py", line 115, in post return request("post", url, data=data, json=json, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/app/venv/lib/python3.11/site-packages/requests/api.py", line 59, in request return session.request(method=method, url=url, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/app/venv/lib/python3.11/site-packages/requests/sessions.py", line 589, in request resp = self.send(prep, **send_kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/app/venv/lib/python3.11/site-packages/requests/sessions.py", line 703, in send r = adapter.send(request, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/app/venv/lib/python3.11/site-packages/requests/adapters.py", line 519, in send raise ConnectionError(e, request=request) requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /translate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6356f946d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Back-off restarting failed container libretranslate in pod libretranslate-0_libretranslate(2d598848-dc4c-473e-a4dd-53cd776cb756)

Fresh install with

```sh
helm repo add libretranslate https://libretranslate.github.io/helm-chart/
helm repo update
helm install libretranslate libretranslate/libretranslate --namespace libretranslate --create-namespace
```

**Comment by linonetwo** [comment]
Also there is no log in container.
